### ISSUE TITLE
Following errors while compiling

### ISSUE THREAD

**Issue by pramodcnair** [gillescochez/angular2-scrolled#1]
Build: Argument of type 'Object' is not assignable to parameter of type 'EventTarget | { addListener: (eventName: string, handler: Function) => void; removeListener: (eve...'. BookingUI.Web   C:\Projects\app\angular2-scrolled\angular2-scrolled.ts  57  

Error   TS2339  Property 'fromEvent' does not exist on type 'typeof Observable'.    TypeScript Virtual Projects C:\Projects\app\angular2-scrolled\angular2-scrolled.ts  57  Active

**Comment by gillescochez** [comment]
Not using TypeScript in the project but it seems to complain about a property missing on Observable which is imported from rxjs so maybe the issue is around the dependency being the wrong version, as Observable seems to be defined, or maybe a TypeScript configuration missing or the porting of the code from JS to Typescript.
